question_data = [
{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"French is an official language in Canada.",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
"correct_answer":"False",
"incorrect_answers":["True"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"The color orange is named after the fruit.",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"You can legally drink alcohol while driving in Mississippi.",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"On average, at least 1 person is killed by a drunk driver in the United States every hour.",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"When you cry in space, your tears stick to your face.",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
"correct_answer":"True",
"incorrect_answers":["False"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
"correct_answer":"False",
"incorrect_answers":["True"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"Scotland voted to become an independent country during the referendum from September 2014.",
"correct_answer":"False",
"incorrect_answers":["True"]},

{"category":"General Knowledge",
"type":"boolean",
"difficulty":"easy",
"question":"Slovakia is a member of European Union-",
"correct_answer":"True",
"incorrect_answers":["False"]}

]